[package]
name = "ciprobe"
version = "1.2.3"
edition = "2021"

[lib]
name = "ciprobe"
path = "src/lib.rs"

[[bin]]
name = "ciprobe"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
dotenv = "0.15"