trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main
variables:
  CARGO_TERM_COLOR: always
jobs:
  - job: test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: cargo test
        displayName: 'Run Tests'
