trigger:
  batch: false
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.md'

pr:
  branches:
    include:
      - main

variables:
  CARGO_TERM_COLOR: always

jobs:
  - job: test
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        windows:
          imageName: 'windows-latest'
        macos:
          imageName: 'macos-latest'
    displayName: Test
    pool:
      vmImage: $(imageName)
    steps:
      - script: cargo test
        displayName: 'Run Tests'
      - script: cargo build
        displayName: 'Verify Build'
