trigger:
  batch: false
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.md'

pr:
  branches:
    include:
      - main

variables:
  CARGO_TERM_COLOR: always

jobs:
  - job: test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: cargo test
        displayName: 'Run Tests'
